# Setup
title:        apuntesDGIIM
tagline:      Apuntes colaborativos del Doble Grado.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       DGIIM
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# Sass
sass:
    load_paths:
        - _sass
        - node_modules


