# Setup
title:        apuntesDGIIM
tagline:      Apuntes colaborativos del Doble Grado.
baseurl:      "https://libreim.github.io/apuntesDGIIM/"
url:          "https://libreim.github.io/apuntesDGIIM/"

# About/contact
author:
  name:       DGIIM
  url:        http://yourhomepage.com


