# Setup
title:        apuntesDGIIM
tagline:      Apuntes colaborativos del Doble Grado.
baseurl:      ""

# About/contact
author:
  name:       DGIIM
  url:        http://yourhomepage.com

# Sass
sass:
    load_paths:
        - _sass


